-- ScentDB: Market Basket Analysis
-- =====================
-- Market basket analysis comes from supermarket research in
-- the 1990s. The original question was simple: if someone
-- puts bread in their cart, what else are they likely to buy?
-- The answer turned out to be useful enough that every serious
-- retail operation in the world now runs some version of it.
--
-- In fragrance retail the question is the same but richer.
-- Fragrances are not commodities — people build collections
-- with intention. Someone who owns Aventus and Sauvage is
-- probably not buying randomly. They have a taste profile
-- that expresses itself through their choices and that
-- profile predicts their next purchase better than any
-- demographic data ever could.
--
-- The three metrics that basket analysis runs on are:
--
-- SUPPORT: how often does this combination appear?
-- Out of all purchases, what fraction include both A and B?
-- Low support means the pattern might be coincidence.
-- High support means it is a genuine behavioral signal.
--
-- CONFIDENCE: given that someone bought A, how likely are
-- they to also buy B? This is the directional version of
-- support. Confidence of 80% means 8 out of 10 people
-- who bought A also bought B. That is actionable.
--
-- LIFT: how much more likely is B given A compared to B
-- on its own? Lift of 1.0 means no relationship — buying A
-- tells you nothing about B. Lift above 2.0 means a strong
-- positive association worth building recommendations around.
-- Lift below 1.0 means buying A actually makes B less likely —
-- the products compete rather than complement.
--
-- These three numbers together tell you what to recommend,
-- how confidently to recommend it, and whether the
-- recommendation is actually adding value or just noise.
-- =====================

-- =====================
-- STEP 1: TRANSACTION ITEMSETS
-- =====================
-- Build the foundation: every user's complete purchase history
-- as a single set of items. This is the raw material that
-- every basket analysis calculation builds on.

WITH user_baskets AS (
    SELECT
        p.user_id,
        u.username,
        u.country,
        ARRAY_AGG(
            f.name ORDER BY p.purchase_date ASC
        ) AS purchased_fragrances,
        ARRAY_AGG(
            b.name ORDER BY p.purchase_date ASC
        ) AS purchased_brands,
        COUNT(DISTINCT p.fragrance_id) AS basket_size,
        SUM(p.price_paid) AS basket_value,
        MIN(p.purchase_date) AS first_purchase,
        MAX(p.purchase_date) AS last_purchase
    FROM purchases p
    JOIN users u ON p.user_id = u.user_id
    JOIN fragrances f ON p.fragrance_id = f.fragrance_id
    JOIN brands b ON f.brand_id = b.brand_id
    GROUP BY p.user_id, u.username, u.country
    HAVING COUNT(DISTINCT p.fragrance_id) >= 1
)
SELECT
    username,
    country,
    purchased_fragrances,
    purchased_brands,
    basket_size,
    ROUND(basket_value, 2) AS basket_value,
    first_purchase,
    last_purchase,
    CASE
        WHEN basket_size >= 4 THEN 'Collector basket'
        WHEN basket_size >= 2 THEN 'Multi-purchase basket'
        ELSE 'Single item basket'
    END AS basket_type
FROM user_baskets
ORDER BY basket_size DESC, basket_value DESC;

-- =====================
-- STEP 2: PAIRWISE SUPPORT CALCULATION
-- =====================
-- For every pair of fragrances that appear together
-- in at least one user's purchase history, calculate
-- the support score — how often this pair appears
-- relative to total transactions.

WITH purchase_pairs AS (
    SELECT
        p1.user_id,
        p1.fragrance_id AS fragrance_a_id,
        f1.name AS fragrance_a,
        b1.name AS brand_a,
        p2.fragrance_id AS fragrance_b_id,
        f2.name AS fragrance_b,
        b2.name AS brand_b
    FROM purchases p1
    JOIN purchases p2
        ON p1.user_id = p2.user_id
        AND p1.fragrance_id < p2.fragrance_id
    JOIN fragrances f1 ON p1.fragrance_id = f1.fragrance_id
    JOIN fragrances f2 ON p2.fragrance_id = f2.fragrance_id
    JOIN brands b1 ON f1.brand_id = b1.brand_id
    JOIN brands b2 ON f2.brand_id = b2.brand_id
),
total_users AS (
    SELECT COUNT(DISTINCT user_id) AS n
    FROM purchases
)
SELECT
    pp.fragrance_a,
    pp.brand_a,
    pp.fragrance_b,
    pp.brand_b,
    COUNT(DISTINCT pp.user_id) AS users_bought_both,
    tu.n AS total_customers,
    -- Support: fraction of all customers who bought both
    ROUND(
        COUNT(DISTINCT pp.user_id)::DECIMAL / tu.n,
        4
    ) AS support,
    ROUND(
        COUNT(DISTINCT pp.user_id)::DECIMAL / tu.n * 100,
        2
    ) AS support_percent,
    -- Revenue generated by users who bought both
    ROUND(
        SUM(p.price_paid),
        2
    ) AS combined_revenue
FROM purchase_pairs pp
CROSS JOIN total_users tu
JOIN purchases p ON p.user_id = pp.user_id
    AND p.fragrance_id IN (pp.fragrance_a_id, pp.fragrance_b_id)
GROUP BY
    pp.fragrance_a, pp.brand_a,
    pp.fragrance_b, pp.brand_b,
    tu.n
ORDER BY support DESC;

-- =====================
-- STEP 3: CONFIDENCE AND LIFT
-- =====================
-- Confidence tells you the direction: given A, how likely is B?
-- Lift normalises confidence against base rate: is this
-- relationship stronger than chance would predict?

WITH item_frequency AS (
    SELECT
        f.name AS fragrance,
        COUNT(DISTINCT p.user_id) AS buyers,
        COUNT(DISTINCT p.user_id)::DECIMAL /
            (SELECT COUNT(DISTINCT user_id) FROM purchases) AS base_rate
    FROM purchases p
    JOIN fragrances f ON p.fragrance_id = f.fragrance_id
    GROUP BY f.name
),
pair_frequency AS (
    SELECT
        f1.name AS fragrance_a,
        f2.name AS fragrance_b,
        COUNT(DISTINCT p1.user_id) AS pair_buyers
    FROM purchases p1
    JOIN purchases p2
        ON p1.user_id = p2.user_id
        AND p1.fragrance_id != p2.fragrance_id
    JOIN fragrances f1 ON p1.fragrance_id = f1.fragrance_id
    JOIN fragrances f2 ON p2.fragrance_id = f2.fragrance_id
    GROUP BY f1.name, f2.name
)
SELECT
    pf.fragrance_a AS if_bought,
    pf.fragrance_b AS then_likely_to_buy,
    ia.buyers AS fragrance_a_buyers,
    ib.buyers AS fragrance_b_buyers,
    pf.pair_buyers AS both_bought,
    -- Confidence: P(B|A) = P(A and B) / P(A)
    ROUND(
        pf.pair_buyers::DECIMAL / NULLIF(ia.buyers, 0),
        4
    ) AS confidence,
    ROUND(
        pf.pair_buyers::DECIMAL / NULLIF(ia.buyers, 0) * 100,
        1
    ) AS confidence_percent,
    -- Lift: confidence / base rate of B
    ROUND(
        (pf.pair_buyers::DECIMAL / NULLIF(ia.buyers, 0)) /
        NULLIF(ib.base_rate, 0),
        3
    ) AS lift,
    -- Interpretation
    CASE
        WHEN (pf.pair_buyers::DECIMAL / NULLIF(ia.buyers, 0)) /
             NULLIF(ib.base_rate, 0) >= 3.0
            THEN 'Very strong association — always recommend together'
        WHEN (pf.pair_buyers::DECIMAL / NULLIF(ia.buyers, 0)) /
             NULLIF(ib.base_rate, 0) >= 2.0
            THEN 'Strong association — recommend with high confidence'
        WHEN (pf.pair_buyers::DECIMAL / NULLIF(ia.buyers, 0)) /
             NULLIF(ib.base_rate, 0) >= 1.5
            THEN 'Moderate association — worth surfacing'
        WHEN (pf.pair_buyers::DECIMAL / NULLIF(ia.buyers, 0)) /
             NULLIF(ib.base_rate, 0) >= 1.0
            THEN 'Weak positive — monitor but do not prioritise'
        ELSE 'Negative association — these products may compete'
    END AS association_strength
FROM pair_frequency pf
JOIN item_frequency ia ON pf.fragrance_a = ia.fragrance
JOIN item_frequency ib ON pf.fragrance_b = ib.fragrance
WHERE pf.pair_buyers >= 1
ORDER BY lift DESC, confidence DESC;

-- =====================
-- STEP 4: BRAND AFFINITY ANALYSIS
-- =====================
-- Do customers who buy from one brand tend to also buy
-- from specific other brands? Brand affinity patterns
-- reveal whether brands are competing for the same wallet
-- or serving complementary needs in a collection.
-- A customer who buys both Creed and Tom Ford is different
-- from one who buys Creed and Versace. The first is building
-- a luxury-only collection. The second is mixing price tiers.
-- Both patterns are useful for different reasons.

WITH brand_pairs AS (
    SELECT
        p1.user_id,
        b1.name AS brand_a,
        b2.name AS brand_b,
        b1.brand_id AS brand_a_id,
        b2.brand_id AS brand_b_id
    FROM purchases p1
    JOIN purchases p2
        ON p1.user_id = p2.user_id
    JOIN fragrances f1 ON p1.fragrance_id = f1.fragrance_id
    JOIN fragrances f2 ON p2.fragrance_id = f2.fragrance_id
    JOIN brands b1 ON f1.brand_id = b1.brand_id
    JOIN brands b2 ON f2.brand_id = b2.brand_id
    WHERE b1.brand_id < b2.brand_id
)
SELECT
    brand_a,
    brand_b,
    COUNT(DISTINCT user_id) AS customers_own_both,
    -- What percentage of brand A buyers also own brand B?
    ROUND(
        COUNT(DISTINCT user_id)::DECIMAL /
        (
            SELECT COUNT(DISTINCT p.user_id)
            FROM purchases p
            JOIN fragrances f ON p.fragrance_id = f.fragrance_id
            WHERE f.brand_id = bp.brand_a_id
        ) * 100,
        1
    ) AS pct_brand_a_buyers_own_brand_b,
    CASE
        WHEN COUNT(DISTINCT user_id) >= 3
            THEN 'Strong brand affinity — bundle opportunities exist'
        WHEN COUNT(DISTINCT user_id) >= 2
            THEN 'Moderate affinity — worth cross-promoting'
        ELSE 'Low affinity — limited cross-brand opportunity'
    END AS affinity_level
FROM brand_pairs bp
GROUP BY brand_a, brand_b, brand_a_id, brand_b_id
ORDER BY customers_own_both DESC;

-- =====================
-- STEP 5: SEQUENTIAL PURCHASE PATTERNS
-- =====================
-- What is the most common order in which people build
-- their fragrance collection? Do most people start with
-- a widely known designer fragrance and graduate toward
-- niche? Or do they jump straight into premium and stay?
-- Sequential patterns reveal the customer journey in a way
-- that static co-purchase analysis cannot.

WITH ordered_purchases AS (
    SELECT
        p.user_id,
        u.username,
        f.name AS fragrance,
        b.name AS brand,
        f.price_usd,
        p.purchase_date,
        ROW_NUMBER() OVER (
            PARTITION BY p.user_id
            ORDER BY p.purchase_date ASC
        ) AS purchase_sequence,
        COUNT(*) OVER (
            PARTITION BY p.user_id
        ) AS total_purchases_by_user
    FROM purchases p
    JOIN users u ON p.user_id = u.user_id
    JOIN fragrances f ON p.fragrance_id = f.fragrance_id
    JOIN brands b ON f.brand_id = b.brand_id
),
sequential_pairs AS (
    SELECT
        op1.username,
        op1.fragrance AS first_fragrance,
        op1.brand AS first_brand,
        op1.price_usd AS first_price,
        op2.fragrance AS second_fragrance,
        op2.brand AS second_brand,
        op2.price_usd AS second_price,
        op2.price_usd - op1.price_usd AS price_movement,
        op1.purchase_date AS first_purchase_date,
        op2.purchase_date AS second_purchase_date,
        op2.purchase_date - op1.purchase_date AS days_between
    FROM ordered_purchases op1
    JOIN ordered_purchases op2
        ON op1.user_id = op2.user_id
        AND op1.purchase_sequence = 1
        AND op2.purchase_sequence = 2
)
SELECT
    first_fragrance,
    first_brand,
    first_price,
    second_fragrance,
    second_brand,
    second_price,
    price_movement,
    days_between,
    CASE
        WHEN price_movement > 100
            THEN 'Traded up significantly — premium pathway'
        WHEN price_movement > 0
            THEN 'Slight trade up — gradual premium migration'
        WHEN price_movement = 0
            THEN 'Same price tier — consistent taste level'
        WHEN price_movement < -100
            THEN 'Traded down — possibly diversifying or budget constrained'
        ELSE 'Slight trade down — exploring accessible options'
    END AS journey_pattern,
    CASE
        WHEN days_between <= 30
            THEN 'Rapid collector — bought again within a month'
        WHEN days_between <= 90
            THEN 'Regular buyer — second purchase within a quarter'
        ELSE 'Considered buyer — took time before returning'
    END AS buying_velocity
FROM sequential_pairs
ORDER BY days_between ASC;

-- =====================
-- STEP 6: AFFINITY SCORING FOR RECOMMENDATIONS
-- =====================
-- Pull everything together into a recommendation-ready
-- affinity score for every fragrance pair in the catalog.
-- This is the table a recommendation engine would query
-- in real time when a user views a product page.
-- High affinity score = show this in the "you might also like" section.
-- Low or negative score = do not surface these together.

WITH all_pairs AS (
    SELECT
        f1.fragrance_id AS frag_a_id,
        f1.name AS fragrance_a,
        b1.name AS brand_a,
        f1.price_usd AS price_a,
        f2.fragrance_id AS frag_b_id,
        f2.name AS fragrance_b,
        b2.name AS brand_b,
        f2.price_usd AS price_b,
        COUNT(DISTINCT p1.user_id) AS co_purchase_count
    FROM purchases p1
    JOIN purchases p2
        ON p1.user_id = p2.user_id
        AND p1.fragrance_id != p2.fragrance_id
    JOIN fragrances f1 ON p1.fragrance_id = f1.fragrance_id
    JOIN fragrances f2 ON p2.fragrance_id = f2.fragrance_id
    JOIN brands b1 ON f1.brand_id = b1.brand_id
    JOIN brands b2 ON f2.brand_id = b2.brand_id
    GROUP BY
        f1.fragrance_id, f1.name, b1.name, f1.price_usd,
        f2.fragrance_id, f2.name, b2.name, f2.price_usd
),
rated_pairs AS (
    SELECT
        r1.fragrance_id AS frag_a_id,
        r2.fragrance_id AS frag_b_id,
        COUNT(DISTINCT r1.user_id) AS co_rating_count,
        AVG(r1.score + r2.score) / 2 AS avg_combined_rating
    FROM ratings r1
    JOIN ratings r2
        ON r1.user_id = r2.user_id
        AND r1.fragrance_id != r2.fragrance_id
    GROUP BY r1.fragrance_id, r2.fragrance_id
)
SELECT
    ap.fragrance_a,
    ap.brand_a,
    ap.price_a,
    ap.fragrance_b,
    ap.brand_b,
    ap.price_b,
    ap.co_purchase_count,
    COALESCE(rp.co_rating_count, 0) AS co_rating_count,
    ROUND(COALESCE(rp.avg_combined_rating, 0), 2) AS avg_combined_rating,
    ABS(ap.price_a - ap.price_b) AS price_distance,
    -- Final affinity score
    ROUND(
        (ap.co_purchase_count * 0.50) +
        (COALESCE(rp.co_rating_count, 0) * 0.30) +
        (COALESCE(rp.avg_combined_rating, 5) / 10 * 0.20),
        3
    ) AS affinity_score,
    CASE
        WHEN ROUND(
            (ap.co_purchase_count * 0.50) +
            (COALESCE(rp.co_rating_count, 0) * 0.30) +
            (COALESCE(rp.avg_combined_rating, 5) / 10 * 0.20),
            3
        ) >= 1.5 THEN 'Feature in recommendations'
        WHEN ROUND(
            (ap.co_purchase_count * 0.50) +
            (COALESCE(rp.co_rating_count, 0) * 0.30) +
            (COALESCE(rp.avg_combined_rating, 5) / 10 * 0.20),
            3
        ) >= 0.8 THEN 'Include in secondary suggestions'
        ELSE 'Do not actively recommend together'
    END AS recommendation_action
FROM all_pairs ap
LEFT JOIN rated_pairs rp
    ON ap.frag_a_id = rp.frag_a_id
    AND ap.frag_b_id = rp.frag_b_id
ORDER BY affinity_score DESC;